export const groceryDeals = [
//   {
//     id: 1,
//     name: "Fresh Organic Apples",
//     brand: "Nature's Best",
//     originalPrice: 299.99,
//     discountedPrice: 199.99,
//     discountPercentage: 33,
//     image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
//     category: "fruits",
//     dealType: "flash-sale",
//     timeLeft: "2h 30m", // Time remaining for flash sale
//     unit: "per kg",
//     rating: 4.7,
//     totalRatings: 128,
//     inStock: true,
//     tags: ["Organic", "Fresh", "Seasonal"]
//   },
//   {
//     id: 2,
//     name: "Whole Wheat Bread",
//     brand: "Daily Bread Co.",
//     originalPrice: 89.99,
//     discountedPrice: 59.99,
//     discountPercentage: 33,
//     image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
//     category: "bakery",
//     dealType: "bogo",
//     dealDescription: "Buy 1 Get 1 Free",
//     unit: "pack of 2",
//     rating: 4.3,
//     totalRatings: 56,
//     inStock: true,
//     tags: ["Whole Wheat", "Fresh Baked"]
//   },
//   {
//     id: 3,
//     name: "Greek Yogurt",
//     brand: "Creamy Delight",
//     originalPrice: 249.99,
//     discountedPrice: 199.99,
//     discountPercentage: 20,
//     image: "https://images.unsplash.com/photo-1567306301408-9b74779a11af?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
//     category: "dairy",
//     dealType: "limited-time",
//     timeLeft: "1d 5h",
//     unit: "500g pack",
//     rating: 4.5,
//     totalRatings: 89,
//     inStock: true,
//     tags: ["High Protein", "Low Fat"]
//   },
//   {
//     id: 4,
//     name: "Organic Eggs",
//     brand: "Farm Fresh",
//     originalPrice: 179.99,
//     discountedPrice: 149.99,
//     discountPercentage: 17,
//     image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
//     category: "dairy",
//     dealType: "combo",
//     dealDescription: "Eggs + Milk Combo",
//     unit: "dozen",
//     rating: 4.8,
//     totalRatings: 204,
//     inStock: true,
//     tags: ["Free Range", "Organic"]
//   },
  {
    id: 5,
    name: "Basmati Rice",
    brand: "Royal Harvest",
    originalPrice: 599.99,
    discountedPrice: 449.99,
    discountPercentage: 25,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    category: "staples",
    dealType: "bulk-discount",
    dealDescription: "Extra 5% off on 2 bags",
    unit: "5kg bag",
    rating: 4.6,
    totalRatings: 156,
    inStock: true,
    tags: ["Premium", "Aged"]
  },
  {
    id: 6,
    name: "Fresh Salmon Fillet",
    brand: "Ocean's Best",
    originalPrice: 899.99,
    discountedPrice: 699.99,
    discountPercentage: 22,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    category: "seafood",
    dealType: "weekend-sale",
    timeLeft: "3d 12h",
    unit: "per kg",
    rating: 4.9,
    totalRatings: 178,
    inStock: true,
    tags: ["Wild Caught", "Fresh"]
  },
  {
    id: 7,
    name: "Mixed Nuts Pack",
    brand: "Healthy Crunch",
    originalPrice: 399.99,
    discountedPrice: 299.99,
    discountPercentage: 25,
    image: "https://images.unsplash.com/photo-1540914124281-342587941389?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    category: "snacks",
    dealType: "member-only",
    dealDescription: "Members Get Extra 10%",
    unit: "500g pack",
    rating: 4.4,
    totalRatings: 92,
    inStock: true,
    tags: ["Unsalted", "Premium Mix"]
  },
  {
    id: 8,
    name: "Avocado",
    brand: "Green Gold",
    originalPrice: 89.99,
    discountedPrice: 69.99,
    discountPercentage: 22,
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    category: "fruits",
    dealType: "flash-sale",
    timeLeft: "45m",
    unit: "each",
    rating: 4.2,
    totalRatings: 67,
    inStock: true,
    tags: ["Hass", "Ready to Eat"]
  }
];

export const dealCategories = [
  { id: 'flash-sale', name: 'Flash Sale', color: 'bg-red-500' },
  { id: 'bogo', name: 'Buy 1 Get 1', color: 'bg-green-500' },
  { id: 'limited-time', name: 'Limited Time', color: 'bg-purple-500' },
  { id: 'member-only', name: 'Member Only', color: 'bg-blue-500' },
  { id: 'weekend-sale', name: 'Weekend Sale', color: 'bg-orange-500' },
  { id: 'bulk-discount', name: 'Bulk Discount', color: 'bg-teal-500' }
];